[package]
name = "bgit"
version = "0.1.0"
edition = "2024"

[dependencies]
hex = "0.4.3"
sha1 = "0.10.5"
tempfile = "3.8.1"
regex = "1.10.2"
chrono = "0.4.40"


[dev-dependencies]
tempfile = "3.10.0"
